-- Migration: formpd_projects v2 — add rich project metadata columns
-- Date: 2026-03-26

ALTER TABLE formpd_projects
  ADD COLUMN category            VARCHAR(50)   NULL COMMENT 'PESQUISA_BASICA|PESQUISA_APLICADA|DESENVOLVIMENTO_EXPERIMENTAL|INOVACAO_TECNOLOGICA',
  ADD COLUMN item_number         INT           NULL COMMENT 'nrItem — position in form listing',
  ADD COLUMN external_id         INT           NULL COMMENT 'idProjeto from MCTI system',
  ADD COLUMN version_number      INT           NULL COMMENT 'nrVersaoAtual',
  ADD COLUMN knowledge_area      VARCHAR(255)  NULL COMMENT 'dsAreaDeConhecimento',
  ADD COLUMN keywords_1          MEDIUMTEXT    NULL COMMENT 'dsPalavrasChave',
  ADD COLUMN keywords_2          MEDIUMTEXT    NULL COMMENT 'dsPalavrasChave2',
  ADD COLUMN keywords_3          MEDIUMTEXT    NULL COMMENT 'dsPalavrasChave3',
  ADD COLUMN keywords_4          MEDIUMTEXT    NULL COMMENT 'dsPalavrasChave4',
  ADD COLUMN keywords_5          MEDIUMTEXT    NULL COMMENT 'dsPalavrasChave5',
  ADD COLUMN innovative_element  MEDIUMTEXT    NULL COMMENT 'dsElementoInovador',
  ADD COLUMN innovative_challenge MEDIUMTEXT   NULL COMMENT 'dsDesafioInovador',
  ADD COLUMN innovative_problem  MEDIUMTEXT    NULL COMMENT 'dsProblemaInovador',
  ADD COLUMN expected_result     MEDIUMTEXT    NULL COMMENT 'dsResultadoEsperado',
  ADD COLUMN project_justification MEDIUMTEXT  NULL COMMENT 'dsJustificativaProjeto',
  ADD COLUMN innovation_risk     MEDIUMTEXT    NULL COMMENT 'dsRiscoInovacao',
  ADD COLUMN expected_impact     MEDIUMTEXT    NULL COMMENT 'dsImpactoEsperado',
  ADD COLUMN external_partnerships MEDIUMTEXT  NULL COMMENT 'dsParceriasExternas',
  ADD COLUMN strategic_alignment MEDIUMTEXT    NULL COMMENT 'dsAlinhamentoEstrategico',
  ADD COLUMN is_collaborative    TINYINT(1)    NOT NULL DEFAULT 0 COMMENT 'icProjetoColaborativo',
  ADD COLUMN economic_result_obtained MEDIUMTEXT NULL COMMENT 'dsResultadoEconomicoObtido',
  ADD COLUMN innovation_result_obtained MEDIUMTEXT NULL COMMENT 'dsResultadoInovacaoObtido',
  ADD COLUMN methodology         MEDIUMTEXT    NULL COMMENT 'dsMetodologiaUtilizada',
  ADD COLUMN additional_info     MEDIUMTEXT    NULL COMMENT 'dsInformacaoComplementar',
  ADD COLUMN continuous_activity_base_year MEDIUMTEXT NULL COMMENT 'dsAtividadeContinuadaAnoBase',
  ADD COLUMN economic_result_objective MEDIUMTEXT NULL COMMENT 'dsObjetivoResultadoEconomico',
  ADD COLUMN innovation_result_objective MEDIUMTEXT NULL COMMENT 'dsObjetivoResultadoInovacao',
  ADD COLUMN research_line_linkage MEDIUMTEXT  NULL COMMENT 'dsVinculacaoMaterialLinhaPesquisa',
  ADD COLUMN area_code           INT           NULL COMMENT 'areaProjeto — numeric area code',
  ADD COLUMN nature_code         INT           NULL COMMENT 'naturezaProjeto — numeric nature code',
  ADD COLUMN pb_pa_or_de         INT           NULL COMMENT 'pbPAouDE: 1=PB,2=PA,3=DE',
  ADD COLUMN justification       MEDIUMTEXT    NULL COMMENT 'dsJustificacao',
  ADD COLUMN trl_initial         INT           NULL COMMENT 'indicacaoNivelDeMaturidadeInicial',
  ADD COLUMN trl_final           INT           NULL COMMENT 'indicacaoNivelDeMaturidadeFinal',
  ADD COLUMN sdg_codes           VARCHAR(500)  NULL COMMENT 'cdObjetivosDesenvolvimentoSustentavel',
  ADD COLUMN sdg_justification   MEDIUMTEXT    NULL COMMENT 'dsJustificativaODS',
  ADD COLUMN area_is_other       TINYINT(1)    NOT NULL DEFAULT 0 COMMENT 'areaProjetoOutro',
  ADD COLUMN area_other_description VARCHAR(500) NULL COMMENT 'dsAreaProjetoOutro',
  ADD COLUMN specific_area       VARCHAR(500)  NULL COMMENT 'areaProjetoEspecifica',
  ADD COLUMN extraction_source   VARCHAR(20)   NOT NULL DEFAULT 'AI' COMMENT 'DETERMINISTIC|AI|MANUAL';
